
org: adamgibbs
app: branching-software
service: branching-software-back

plugins:
  - serverless-dynamodb-local
  - serverless-offline

package:
  exclude:
    - node_modules/dynamodb-localhost/**
    - node_modules/serverless-dynamodb-local/**
    - node_modules/serverless-offline/**

custom:
  tablePrefix: branching-software-table-${self:provider.stage}
  usersTable: users-${self:custom.tablePrefix}
  assetsTable: assets-${self:custom.tablePrefix}

  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations
    stages:
      - dev

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  lambdaHashingVersion: 20201221
  stage: dev
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource: "*"

  environment:
    USERS_TABLE: ${self:custom.usersTable}
    ASSETS_TABLE: ${self:custom.assetsTable}

functions:
  signup:
    handler: server/signup.signup
    events:
      - http:
          path: v1/signup
          method: post
          cors: true

  signin:
    handler: server/signin.signin
    events:
      - http:
          path: v1/signin
          method: post
          cors: true

  addAsset:
    handler: server/addAsset.addAsset
    events:
      - http:
          path: v1/asset/add
          method: post
          cors: true

  allAssets:
    handler: server/allAssets.allAssets
    events:
      - http:
          path: v1/asset/all
          method: post
          cors: true

  hi:
    handler: server/hi.hi
    events:
      - http:
          path: v1/hi
          method: get
          cors: true

resources:
  Resources:
    UsersTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: email
            AttributeType: S
        KeySchema:
          -
            AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.usersTable}

    AssetsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: userId
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: userId-asset-index
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.assetsTable}