
org: adamgibbs
app: branching-software
service: branching-software-back

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  tablePrefix: branching-software-table-${self:provider.stage}
  usersTable: users-${self:custom.tablePrefix}
  assetsTable: assets-${self:custom.tablePrefix}

  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations
    stages:
      - dev

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  stage: dev
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem

  environment:
    USERS_TABLE: ${self:custom.usersTable}
    ASSETS_TABLE: ${self:custom.assetsTable}

functions:
  signup:
    handler: server/signup.signup
    events:
      - http:
          path: v1/signup
          method: post
          cors: true

  signin:
    handler: server/signin.signin
    events:
      - http:
          path: v1/signin
          method: post
          cors: true

  addAsset:
    handler: server/addAsset.addAsset
    events:
      - http:
          path: v1/asset/add
          method: post
          cors: true


  hi:
    handler: server/hi.hi
    events:
      - http:
          path: v1/hi
          method: get
          cors: true

resources:
  Resources:
    UsersTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: email
            AttributeType: S
        KeySchema:
          -
            AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.usersTable}

    AssetsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.assetsTable}